name: Build APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ runner.home }}/.buildozer/android/platform/android-sdk
      ANDROID_SDK_ROOT: ${{ runner.home }}/.buildozer/android/platform/android-sdk
      PATH: ${{ runner.home }}/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:${{ runner.home }}/.buildozer/android/platform/android-sdk/platform-tools:${{ env.PATH }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java (required by Android SDK)
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Ubuntu packages
      run: |
        sudo apt update
        sudo apt install -y build-essential libssl-dev libffi-dev \
          python3-dev python3-pip python3-setuptools unzip zip wget curl git \
          zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libsqlite3-dev \
          libreadline-dev libbz2-dev liblzma-dev

    - name: Install buildozer & Cython
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install buildozer cython

    - name: Create Android SDK directory
      run: |
        mkdir -p $ANDROID_HOME
        mkdir -p $ANDROID_HOME/cmdline-tools

    - name: Download Android command line tools
      run: |
        cd $HOME
        # download latest commandline tools; URL may change in the future
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
        # move to "latest" dir expected by sdkmanager usage
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        rm cmdline-tools.zip

    - name: Install Android SDK packages (platform-tools, platform 33, build-tools 33.0.2)
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --install "platform-tools" "platforms;android-33" "build-tools;33.0.2" "platforms;android-33"

    - name: Accept Android SDK licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses || true

    - name: Show sdkmanager list (debug)
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --list

    - name: Build APK
      env:
        # ensure buildozer can find Android SDK / NDK locations under ~/.buildozer
        ANDROID_HOME: ${{ runner.home }}/.buildozer/android/platform/android-sdk
      run: |
        # run buildozer; it will download python-for-android etc and use SDK we installed
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
