name: Build APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
      PATH: ${{ github.workspace }}/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/.buildozer/android/platform/android-sdk/platform-tools:${{ env.PATH }}

    steps:
    - name: Install tar
      run: sudo apt update && sudo apt install -y tar unzip wget curl git

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java (required by Android SDK)
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Ubuntu packages
      run: |
        sudo apt update
        sudo apt install -y build-essential libssl-dev libffi-dev \
          python3-dev python3-pip python3-setuptools unzip zip wget curl git \
          zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libsqlite3-dev \
          libreadline-dev libbz2-dev liblzma-dev

    - name: Install Buildozer & Cython
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install buildozer cython

    - name: Create Android SDK directories
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools

    - name: Download Android command line tools
      run: |
        cd $HOME
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        rm cmdline-tools.zip

    - name: Install Android SDK packages
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
          "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Accept Android SDK licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses || true

    - name: Build APK
      env:
        ANDROID_HOME: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
